name: Continus Integration
on: [push]
jobs:
  router:
    name: Besoin d'un job ?
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.0.3']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup php, with composer and extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependancies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hasFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependancies
        run: |
          composer install --no-progess --no-suggest --prefer-dist --optimize-autoloader
      - name: Run php coder sniffer
        run: php vendor/bin/phpcs
      - name: Run Acceptance Tests
        run: php  vendo/bin/behat --config behat.yaml
      - name: Run Tests
        run: php vendor/bin/simple-phpunit --testsuite unit,integration